apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: all1q3j55-python
  janus-idp.io/tekton: all1q3j55-python
  backstage.io/kubernetes-id: all1q3j55-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: all1q3j55-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
